<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html dir="ltr" lang="en"> 
  <head>
    <title>Reverskell - A Haskell web implementation of Reversi</title>
    <link rel="stylesheet" type="text/css" media="all" href="/style/style.css" /> 
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta http-equiv="Content-Language" content="en" /> 
  </head>
  <body>

