<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html dir="ltr" lang="en"> 
  <head>
    <title>Reverskell - A Haskell web implementation of Reversi</title>
    <link rel="stylesheet" type="text/css" media="all" href="/style/style.css" /> 
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta http-equiv="Content-Language" content="en" /> 
    <script type="text/javascript" src="/scripts/jquery-1.6.1.min.js"></script>
    <script type="text/javascript" src="/scripts/play.js"></script>
    <script type="text/javascript" src="/scripts/create.js"></script>
  </head>
  <body>
  
  <div id="wrapper">

